<?php
return[
        'key' => 'layout_66265885e4b55',
        'name' => 'features_section',
        'label' => 'Features Section',
        'display' => 'block',
        'sub_fields' => [
            [
                'key' => 'field_66265885e4b56',
                'label' => 'Features background Image',
                'name' => 'features_background_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'return_format' => 'url',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ],
            [
                'key' => 'field_66265885e4b58',
                'label' => 'Features Heading',
                'name' => 'features_heading',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            [
                'key' => 'field_66265885e4b59',
                'label' => 'Features Description',
                'name' => 'features_description',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            [
                'key' => 'field_66265aa7e4b5a',
                'label' => 'Feature Box',
                'name' => 'feature_box',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'block',
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Add Row',
                'rows_per_page' => 20,
                'sub_fields' => [
                    [
                        'key' => 'field_66265abce4b5b',
                        'label' => 'Feature Box Heading',
                        'name' => 'feature_box_heading',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => false,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_66265aa7e4b5a',
                    ],
                    [
                        'key' => 'field_66265ad5e4b5c',
                        'label' => 'Feature Box Description',
                        'name' => 'feature_box_description',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => false,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_66265aa7e4b5a',
                    ],
                ],
            ],
            [
                'key' => 'field_66265b6e30604',
                'label' => 'View More Button link',
                'name' => 'view_more_button_link',
                'aria-label' => '',
                'type' => 'page_link',
                'instructions' => '',
                'required' => false,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'post_type' => [
                    0 => 'page',
                ],
                'taxonomy' => '',
                'allow_archives' => 1,
                'multiple' => 0,
                'allow_null' => 0,
            ],
        ],
        'min' => '',
        'max' => '',
    ];