<?php
return[
	'key' => 'layout_66263ed278a98',
	'name' => 'hero_banner',
	'label' => 'Hero Banner',
	'display' => 'block',
	'sub_fields' => [
		[
			'key' => 'field_66263ef5b4884',
			'label' => 'Banner background Image',
			'name' => 'banner_background_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => false,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		],
		[
			'key' => 'field_66263f0cb4885',
			'label' => 'Banner Side Image',
			'name' => 'banner_side_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => false,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		],
		[
			'key' => 'field_66263f2bb4886',
			'label' => 'Banner Heading',
			'name' => 'banner_heading',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => false,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		],
		[
			'key' => 'field_66263f39b4887',
			'label' => 'Banner Description',
			'name' => 'banner_description',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => false,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		],
	],
	'min' => '',
	'max' => '',
];