<?php
return [
    'key' => 'layout_662a408df5eff',
    'name' => 'image_with_text_section',
    'label' => 'Image with text section',
    'display' => 'block',
    'sub_fields' => array(
      array(
        'key' => 'field_662a40eff5f09',
        'label' => 'IMT Background Image',
        'name' => 'imt_background_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'medium',
      ),
      array(
        'key' => 'field_662a408df5f00',
        'label' => 'IMT Text',
        'name' => 'imt_text',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Lorem Ipsum',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_662a40d4f5f08',
        'label' => 'IMT Description',
        'name' => 'imt_description',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Venenatis ornare in turpis nisl urna. Laoreet ut convallis eu, aliquam habitant phasellus dui ipsum vel. Arcu mauris vel, eu non ut. Vitae ut arcu condimentum tempus tortor risus.',
        'maxlength' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_662a4117f5f0a',
        'label' => 'IMT Thumb Image',
        'name' => 'imt_thumb_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'preview_size' => 'medium',
      ),
    ),
    'min' => '',
    'max' => '',
];