<?php 
return [
					'key' => 'layout_6628afff294b0',
					'name' => 'knowledge_testimonials_section',
					'label' => 'Knowledge Testimonial Section',
					'display' => 'block',
					'sub_fields' => [
						[
							'key' => 'field_66290a2d294b1',
							'label' => 'Knowledge Base Heading',
							'name' => 'knowledge_base_heading',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => false,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'default_value' => 'Knowledge Base',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						],
						[
							'key' => 'field_6629fbb94b645',
							'label' => 'Knowledge Base Description',
							'name' => 'knowledge_base_description',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => false,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						],
						[
							'key' => 'field_6629fbdf4b646',
							'label' => 'Knowledge Base View All Button Link',
							'name' => 'knowledge_base_view_all_button_link',
							'aria-label' => '',
							'type' => 'page_link',
							'instructions' => '',
							'required' => false,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'post_type' => '',
							'taxonomy' => '',
							'allow_archives' => 1,
							'multiple' => 0,
							'allow_null' => 0,
						],
						[
							'key' => 'field_6629fc0b4b647',
							'label' => 'Testimonial Heading',
							'name' => 'testimonial_heading',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => false,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'default_value' => 'Testimonials',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						],
						[
							'key' => 'field_6629fc1e4b648',
							'label' => 'Testimonial Description',
							'name' => 'testimonial_description',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => false,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'default_value' => 'Sed ut vel adipiscing nulla libero lorem.',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						],
						[
							'key' => 'field_6629fc5b4b649',
							'label' => 'User Testimonial',
							'name' => 'user_testimonial',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => false,
							'conditional_logic' => 0,
							'wrapper' => [
								'width' => '',
								'class' => '',
								'id' => '',
							],
							'layout' => 'block',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => [
								[
									'key' => 'field_6629fc8d4b64a',
									'label' => 'Testimonial Username',
									'name' => 'testimonial_username',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => false,
									'conditional_logic' => 0,
									'wrapper' => [
										'width' => '',
										'class' => '',
										'id' => '',
									],
									'default_value' => 'Joe Bloggs',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_6629fc5b4b649',
								],
								[
									'key' => 'field_6629fca24b64b',
									'label' => 'Testimonial Text',
									'name' => 'testimonial_text',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => false,
									'conditional_logic' => 0,
									'wrapper' => [
										'width' => '',
										'class' => '',
										'id' => '',
									],
									'default_value' => '“Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque cum enim, sed”',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_6629fc5b4b649',
								],
							],
						],
					],
					'min' => '',
					'max' => '',
        ];