<?php
return [
	'key' => 'layout_65670e5e792ad',
	'name' => 'posts_section',
	'label' => 'Posts Section',
	'display' => 'block',
	'sub_fields'  => [
        [
            'key' => 'field_66263ef5b4994',
            'label' => 'Posts Section background Image',
            'name' => 'post_background_image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => false,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'return_format' => 'url',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'medium',
        ],
        [
            'key' => 'field_65dc891d322e0',
            'label' => 'Post Main Heading',
            'name' => 'post_main_heading',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => false,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '50',
                'class' => '',
                'id' => '',
            ],
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
		[
            'key' => 'field_65dc891d322f0',
            'label' => 'Post Description',
            'name' => 'post_desc',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => false,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '50',
                'class' => '',
                'id' => '',
            ],
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
			'key' => 'field_66266987d519c',
			'label' => 'View All Button Link',
			'name' => 'view_all_button_link',
			'aria-label' => '',
			'type' => 'page_link',
			'instructions' => '',
			'required' => false,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'post_type' => '',
			'taxonomy' => '',
			'allow_archives' => 1,
			'multiple' => 0,
			'allow_null' => 0,
		],
	],
	'min' => '',
	'max' => '',
];